<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>ClassManager.Infrastructure</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../Core/Core.csproj" />
    <ProjectReference Include="../Notifications.Delivery/Notifications.Delivery.csproj" />
    <ProjectReference Include="../Security/Security.csproj" />
    <ProjectReference Include="../Subscriptions.AspNetCore/Subscriptions.AspNetCore.csproj" />
    <ProjectReference Include="../Tenancy.AspNetCore/Tenancy.AspNetCore.csproj" />
  </ItemGroup>
  <ItemGroup>
    <AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleToAttribute">
      <_Parameter1>ClassManager.Api.I.Tests</_Parameter1>
    </AssemblyAttribute>
  </ItemGroup>
</Project>
