export const routes = {
  today: "/today",
  session: (classGroupId: string, sessionDate: string) => `/today/${classGroupId}/${sessionDate}`,
  classes: "/classes",
  newClassGroup: (weekday?: string) =>
    weekday ? `/classes/new?weekday=${encodeURIComponent(weekday)}` : "/classes/new",
  classGroup: (classGroupId: string) => `/classes/${classGroupId}`,
  editClassGroup: (classGroupId: string) => `/classes/${classGroupId}/edit`,
  enrollStudent: (classGroupId: string) => `/classes/${classGroupId}/enroll`,
  students: "/students",
  registerClient: "/students/new",
  clientDetail: (clientId: string) => `/students/clients/${clientId}`,
  addStudent: (clientId: string) => `/students/clients/${clientId}/new-student`,
  signIn: "/sign-in",
  signUp: "/sign-up",
  settings: "/settings",
  businessSettings: "/settings/business",
  instructors: "/settings/instructors",
  newInstructor: "/settings/instructors/new",
  instructor: (instructorId: string) => `/settings/instructors/${instructorId}`,
} as const;
