export const routes = {
  today: "/today",
  session: (classGroupId: string, sessionDate: string) => `/today/${classGroupId}/${sessionDate}`,
  newPrivateLesson: (date: string) => `/today/private/new?date=${encodeURIComponent(date)}`,
  privateLesson: (privateLessonId: string) => `/today/private/${privateLessonId}`,
  editPrivateLesson: (privateLessonId: string) => `/today/private/${privateLessonId}/edit`,
  classes: "/classes",
  newClassGroup: (weekday?: string) =>
    weekday ? `/classes/new?weekday=${encodeURIComponent(weekday)}` : "/classes/new",
  classGroup: (classGroupId: string) => `/classes/${classGroupId}`,
  editClassGroup: (classGroupId: string) => `/classes/${classGroupId}/edit`,
  enrollStudent: (classGroupId: string) => `/classes/${classGroupId}/enroll`,
  students: "/students",
  registerClient: "/students/new",
  clientDetail: (clientId: string) => `/students/clients/${clientId}`,
  addStudent: (clientId: string) => `/students/clients/${clientId}/new-student`,
  sellClassPack: (clientId: string) => `/students/clients/${clientId}/sell-pack`,
  clientCounterSale: (clientId: string) => `/students/clients/${clientId}/counter-sale`,
  fees: "/fees",
  recordPayment: (clientId: string, month: string) =>
    `/fees/${clientId}/pay?month=${encodeURIComponent(month)}`,
  welcome: "/welcome",
  signIn: "/sign-in",
  signUp: "/sign-up",
  resetPassword: "/reset-password",
  forgotPassword: (email: string) =>
    email ? `/forgot-password?email=${encodeURIComponent(email)}` : "/forgot-password",
  settings: "/settings",
  businessSettings: "/settings/business",
  defaultMonthlyFee: "/settings/monthly-fee",
  instructors: "/settings/instructors",
  newInstructor: "/settings/instructors/new",
  instructor: (instructorId: string) => `/settings/instructors/${instructorId}`,
  classPacks: "/settings/class-packs",
  newClassPack: "/settings/class-packs/new",
  classPack: (classPackId: string) => `/settings/class-packs/${classPackId}`,
  products: "/settings/products",
  newProduct: "/settings/products/new",
  product: (productId: string) => `/settings/products/${productId}`,
  orders: "/settings/orders",
  newCounterSale: "/settings/orders/new",
  importExport: "/settings/import-export",
  team: "/settings/team",
  inviteMember: "/settings/team/invite",
  teamMember: (memberId: string) => `/settings/team/${memberId}`,
  roles: "/settings/roles",
  newRole: (copyFromRoleKey?: string) =>
    copyFromRoleKey
      ? `/settings/roles/new?copyFrom=${encodeURIComponent(copyFromRoleKey)}`
      : "/settings/roles/new",
  role: (roleKey: string) => `/settings/roles/${roleKey}`,
  acceptInvitation: "/accept-invitation",
  acceptFamilyInvitation: "/accept-family-invitation",
  family: "/family",
  familyShop: "/family/shop",
  familyOrders: "/family/orders",
  branches: "/settings/branches",
  newBranch: "/settings/branches/new",
} as const;
