<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>ClassManager.Notifications.Delivery</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="MailKit" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../Notifications/Notifications.csproj" />
  </ItemGroup>
  <ItemGroup>
    <AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleToAttribute">
      <_Parameter1>ClassManager.Notifications.U.Tests</_Parameter1>
    </AssemblyAttribute>
  </ItemGroup>
</Project>
