<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <NoWarn>$(NoWarn);CA1707</NoWarn>
    <RootNamespace>ClassManager.Analyzers.Tests</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp" />
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp.Workspaces" />
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp.Analyzer.Testing" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../../analyzers/ClassManager.Analyzers/ClassManager.Analyzers.csproj" />
  </ItemGroup>
</Project>
