<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <RootNamespace>ClassManager.Storage.I.Tests</RootNamespace>
    <NoWarn>$(NoWarn);CA1707</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
    <PackageReference Include="Shouldly" />
    <PackageReference Include="Testcontainers.Azurite" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/Storage/Storage.csproj" />
    <ProjectReference Include="../../src/Storage.AzureBlob/Storage.AzureBlob.csproj" />
  </ItemGroup>
</Project>
