FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build
WORKDIR /source

COPY NuGet.config Directory.Build.props Directory.Packages.props ./
COPY analyzers/ analyzers/
COPY src/ src/

RUN dotnet restore src/Api/Api.csproj
RUN dotnet publish src/Api/Api.csproj --configuration Release --no-restore --output /app

FROM mcr.microsoft.com/dotnet/aspnet:10.0 AS runtime
WORKDIR /app
COPY --from=build /app ./

USER $APP_UID
EXPOSE 8080
ENTRYPOINT ["dotnet", "Api.dll"]
