using ClassManager.Core.Abstractions.Fees;
using ClassManager.Core.Abstractions.Images;
using ClassManager.Core.Abstractions.Security;
using ClassManager.Core.Abstractions.Time;
using ClassManager.Core.Services;
using ClassManager.Core.UseCases.Accounts;
using ClassManager.Core.UseCases.Achievements;
using ClassManager.Core.UseCases.Announcements;
using ClassManager.Core.UseCases.Authentication;
using ClassManager.Core.UseCases.Branches;
using ClassManager.Core.UseCases.Brands;
using ClassManager.Core.UseCases.Businesses;
using ClassManager.Core.UseCases.ClassGroups;
using ClassManager.Core.UseCases.ClassPacks;
using ClassManager.Core.UseCases.Clients;
using ClassManager.Core.UseCases.Enrollments;
using ClassManager.Core.UseCases.Fees;
using ClassManager.Core.UseCases.ImportExport;
using ClassManager.Core.UseCases.ImportExport.Instructors;
using ClassManager.Core.UseCases.ImportExport.Students;
using ClassManager.Core.UseCases.Instructors;
using ClassManager.Core.UseCases.Members;
using ClassManager.Core.UseCases.Orders;
using ClassManager.Core.UseCases.PrivateLessons;
using ClassManager.Core.UseCases.Products;
using ClassManager.Core.UseCases.Roles;
using ClassManager.Core.UseCases.Sessions;
using ClassManager.Core.UseCases.StudentApp;
using ClassManager.Core.UseCases.Students;
using ClassManager.Core.UseCases.Subscriptions;
using ClassManager.Core.UseCases.TeamNotifications;
using ClassManager.ImportExport.Parsing;
using ClassManager.ImportExport.Tabular;
using ClassManager.ImportExport.Tabular.Csv;
using ClassManager.ImportExport.Xlsx;

namespace ClassManager.Api;

internal static class UseCaseServiceCollectionExtensions
{
    public static IServiceCollection AddUseCases(this IServiceCollection services)
    {
        services.AddSingleton(TimeProvider.System);
        services.AddScoped<IBusinessCalendarService, BusinessCalendarService>();
        services.AddScoped<IClassBalanceService, ClassBalanceService>();
        services.AddScoped<ICatalogImageService, CatalogImageService>();
        services.AddScoped<IAccessScopes, AccessScopes>();
        services.AddSingleton<CsvTabularReader>();
        services.AddSingleton(new XlsxTabularReader());
        services.AddSingleton<ITabularReader, XlsxOrCsvTabularReader>();
        services.AddSingleton<ITabularWriter, XlsxTabularWriter>();
        services.AddSingleton<IImportParser, ImportParser>();
        services.AddScoped<IImportModule, InstructorImportModule>();
        services.AddScoped<IImportModule, StudentImportModule>();
        services.AddScoped(typeof(IUseCaseBehavior<,>), typeof(CommandTransactionBehavior<,>));
        services.AddScoped(typeof(IUseCaseBehavior<,>), typeof(QueryNoTrackingBehavior<,>));

        services.AddUseCase<SignUpOwnerCommand, TokenResponse, SignUpOwnerUseCase>();
        services.AddUseCase<GetImportSchemaQuery, ImportSchemaResponse, GetImportSchemaUseCase>();
        services.AddUseCase<PreviewImportCommand, ImportReport, PreviewImportUseCase>();
        services.AddUseCase<ImportFileCommand, ImportReport, ImportFileUseCase>();
        services.AddUseCase<GetImportTemplateQuery, ExportFile, GetImportTemplateUseCase>();
        services.AddUseCase<ExportQuery, ExportFile, ExportUseCase>();
        services.AddUseCase<SignInCommand, TokenResponse, SignInUseCase>();
        services.AddUseCase<ListAccountsQuery, IReadOnlyList<AccountResponse>, ListAccountsUseCase>();
        services.AddUseCase<RefreshSessionCommand, TokenResponse, RefreshSessionUseCase>();
        services.AddUseCase<SignOutCommand, SignOutResponse, SignOutUseCase>();
        services.AddUseCase<ResetPasswordCommand, ResetPasswordResponse, ResetPasswordUseCase>();
        services.AddUseCase<RequestPasswordResetCommand, RequestPasswordResetResponse, RequestPasswordResetUseCase>();
        services.AddUseCase<GetMyAccountQuery, MyAccountResponse, GetMyAccountUseCase>();
        services.AddUseCase<UpdateMyProfileCommand, MyAccountResponse, UpdateMyProfileUseCase>();
        services.AddUseCase<RequestEmailChangeCommand, RequestEmailChangeResponse, RequestEmailChangeUseCase>();
        services.AddUseCase<ConfirmEmailChangeCommand, ConfirmEmailChangeResponse, ConfirmEmailChangeUseCase>();
        services.AddUseCase<GetCurrentBusinessQuery, BusinessResponse, GetCurrentBusinessUseCase>();
        services.AddUseCase<GetBrandQuery, BrandResponse, GetBrandUseCase>();
        services.AddUseCase<UpdateBrandCommand, BrandResponse, UpdateBrandUseCase>();
        services.AddUseCase<SetBrandLogoCommand, BrandResponse, SetBrandLogoUseCase>();
        services.AddUseCase<RemoveBrandLogoCommand, BrandResponse, RemoveBrandLogoUseCase>();
        services.AddUseCase<GetBrandLogoQuery, BrandLogoFile, GetBrandLogoUseCase>();
        services.AddUseCase<GetCurrentMemberQuery, CurrentMemberResponse, GetCurrentMemberUseCase>();
        services.AddUseCase<ListPlansQuery, IReadOnlyList<PlanResponse>, ListPlansUseCase>();
        services.AddUseCase<GetOrganizationSubscriptionQuery, OrganizationSubscriptionResponse, GetOrganizationSubscriptionUseCase>();
        services.AddUseCase<GetTeamQuery, TeamResponse, GetTeamUseCase>();
        services.AddUseCase<InviteMemberCommand, InvitationResponse, InviteMemberUseCase>();
        services.AddUseCase<RevokeInvitationCommand, RevokedInvitationResponse, RevokeInvitationUseCase>();
        services.AddUseCase<ResendInvitationCommand, InvitationResponse, ResendInvitationUseCase>();
        services.AddUseCase<AcceptInvitationCommand, TokenResponse, AcceptInvitationUseCase>();
        services.AddUseCase<CheckInvitationCommand, CheckInvitationResponse, CheckInvitationUseCase>();
        services.AddUseCase<DeclineInvitationCommand, DeclinedInvitationResponse, DeclineInvitationUseCase>();
        services.AddUseCase<ChangeMemberRoleCommand, MemberResponse, ChangeMemberRoleUseCase>();
        services.AddUseCase<RemoveMemberCommand, RemovedMemberResponse, RemoveMemberUseCase>();
        services.AddUseCase<ListBranchesQuery, IReadOnlyList<BranchResponse>, ListBranchesUseCase>();
        services.AddUseCase<SwitchBranchCommand, TokenResponse, SwitchBranchUseCase>();
        services.AddUseCase<CreateBranchCommand, BranchResponse, CreateBranchUseCase>();
        services.AddUseCase<SetBrandOwnerCommand, BrandOwnerResponse, SetBrandOwnerUseCase>();
        services.AddUseCase<RegisterClientCommand, ClientDetailsResponse, RegisterClientUseCase>();
        services.AddUseCase<GetClientQuery, ClientDetailsResponse, GetClientUseCase>();
        services.AddUseCase<UpdateClientCommand, ClientResponse, UpdateClientUseCase>();
        services.AddUseCase<SearchClientsQuery, IReadOnlyList<ClientResponse>, SearchClientsUseCase>();
        services.AddUseCase<AddStudentCommand, StudentResponse, AddStudentUseCase>();
        services.AddUseCase<GetStudentQuery, StudentSummaryResponse, GetStudentUseCase>();
        services.AddUseCase<SearchStudentsQuery, IReadOnlyList<StudentSummaryResponse>, SearchStudentsUseCase>();
        services.AddUseCase<ListInstructorsQuery, IReadOnlyList<InstructorResponse>, ListInstructorsUseCase>();
        services.AddUseCase<CreateInstructorCommand, InstructorResponse, CreateInstructorUseCase>();
        services.AddUseCase<UpdateInstructorCommand, InstructorResponse, UpdateInstructorUseCase>();
        services.AddUseCase<SetInstructorActiveCommand, InstructorResponse, SetInstructorActiveUseCase>();
        services.AddUseCase<ListClassGroupsQuery, IReadOnlyList<ClassGroupResponse>, ListClassGroupsUseCase>();
        services.AddUseCase<GetClassGroupQuery, ClassGroupResponse, GetClassGroupUseCase>();
        services.AddUseCase<CreateClassGroupCommand, ClassGroupResponse, CreateClassGroupUseCase>();
        services.AddUseCase<UpdateClassGroupCommand, ClassGroupResponse, UpdateClassGroupUseCase>();
        services.AddUseCase<SetClassGroupActiveCommand, ClassGroupResponse, SetClassGroupActiveUseCase>();
        services.AddUseCase<UploadClassMaterialFileCommand, ClassGroupResponse, UploadClassMaterialFileUseCase>();
        services.AddUseCase<RemoveClassMaterialFileCommand, ClassGroupResponse, RemoveClassMaterialFileUseCase>();
        services.AddUseCase<EnrollStudentCommand, EnrollmentResponse, EnrollStudentUseCase>();
        services.AddUseCase<EndEnrollmentCommand, EndEnrollmentResponse, EndEnrollmentUseCase>();
        services.AddUseCase<ListClassRosterQuery, IReadOnlyList<RosterEntryResponse>, ListClassRosterUseCase>();
        services.AddUseCase<ListStudentEnrollmentsQuery, IReadOnlyList<StudentEnrollmentResponse>, ListStudentEnrollmentsUseCase>();
        services.AddUseCase<ListDaySessionsQuery, IReadOnlyList<DaySessionResponse>, ListDaySessionsUseCase>();
        services.AddUseCase<ListMonthCalendarQuery, MonthCalendarResponse, ListMonthCalendarUseCase>();
        services.AddUseCase<SchedulePrivateLessonCommand, IReadOnlyList<PrivateLessonResponse>, SchedulePrivateLessonUseCase>();
        services.AddUseCase<GetPrivateLessonQuery, PrivateLessonResponse, GetPrivateLessonUseCase>();
        services.AddUseCase<ReschedulePrivateLessonCommand, PrivateLessonResponse, ReschedulePrivateLessonUseCase>();
        services.AddUseCase<CancelPrivateLessonCommand, PrivateLessonResponse, CancelPrivateLessonUseCase>();
        services.AddUseCase<RestorePrivateLessonCommand, PrivateLessonResponse, RestorePrivateLessonUseCase>();
        services.AddUseCase<RecordPrivateLessonAttendanceCommand, RecordAttendanceResponse, RecordPrivateLessonAttendanceUseCase>();
        services.AddUseCase<DeletePrivateLessonCommand, DeletedPrivateLessonResponse, DeletePrivateLessonUseCase>();
        services.AddUseCase<GetSessionQuery, SessionDetailsResponse, GetSessionUseCase>();
        services.AddUseCase<RecordAttendanceCommand, RecordAttendanceResponse, RecordAttendanceUseCase>();
        services.AddUseCase<RecordClassFeedbackCommand, bool, RecordClassFeedbackUseCase>();
        services.AddUseCase<CancelSessionCommand, SessionStatusResponse, CancelSessionUseCase>();
        services.AddUseCase<RestoreSessionCommand, SessionStatusResponse, RestoreSessionUseCase>();
        services.AddUseCase<RescheduleSessionCommand, SessionStatusResponse, RescheduleSessionUseCase>();
        services.AddUseCase<RestoreSessionScheduleCommand, SessionStatusResponse, RestoreSessionScheduleUseCase>();
        services.AddUseCase<GetStudentAppHomeQuery, StudentAppHomeResponse, GetStudentAppHomeUseCase>();
        services.AddUseCase<GetStudentAppNewsQuery, StudentAppNewsResponse, GetStudentAppNewsUseCase>();
        services.AddUseCase<MarkStudentAppNewsSeenCommand, bool, MarkStudentAppNewsSeenUseCase>();
        services.AddUseCase<NotifyAbsenceCommand, bool, NotifyAbsenceUseCase>();
        services.AddScoped<MakeupRepositories>();
        services.AddScoped<PackCreditRepositories>();
        services.AddUseCase<GetStudentAppPushKeyQuery, StudentAppPushKeyResponse, GetStudentAppPushKeyUseCase>();
        services.AddUseCase<SavePushSubscriptionCommand, bool, SavePushSubscriptionUseCase>();
        services.AddUseCase<RemovePushSubscriptionCommand, bool, RemovePushSubscriptionUseCase>();
        services.AddUseCase<GetTeamNotificationsQuery, TeamNotificationsResponse, GetTeamNotificationsUseCase>();
        services.AddUseCase<MarkTeamNotificationsSeenCommand, bool, MarkTeamNotificationsSeenUseCase>();
        services.AddUseCase<GetTeamPushKeyQuery, TeamPushKeyResponse, GetTeamPushKeyUseCase>();
        services.AddUseCase<SaveTeamPushSubscriptionCommand, bool, SaveTeamPushSubscriptionUseCase>();
        services.AddUseCase<RemoveTeamPushSubscriptionCommand, bool, RemoveTeamPushSubscriptionUseCase>();
        services.AddUseCase<GetStudentAppMakeupsQuery, StudentAppMakeupsResponse, GetStudentAppMakeupsUseCase>();
        services.AddUseCase<BookMakeupCommand, bool, BookMakeupUseCase>();
        services.AddUseCase<CancelMakeupCommand, bool, CancelMakeupUseCase>();
        services.AddUseCase<GetStudentAppPackClassesQuery, StudentAppPackClassesResponse, GetStudentAppPackClassesUseCase>();
        services.AddUseCase<BookPackClassCommand, bool, BookPackClassUseCase>();
        services.AddUseCase<CancelPackClassCommand, bool, CancelPackClassUseCase>();
        services.AddUseCase<WithdrawAbsenceCommand, bool, WithdrawAbsenceUseCase>();
        services.AddUseCase<CreateAnnouncementCommand, AnnouncementResponse, CreateAnnouncementUseCase>();
        services.AddUseCase<ListAnnouncementsQuery, IReadOnlyList<AnnouncementResponse>, ListAnnouncementsUseCase>();
        services.AddUseCase<DeleteAnnouncementCommand, bool, DeleteAnnouncementUseCase>();
        services.AddUseCase<RestoreAnnouncementCommand, bool, RestoreAnnouncementUseCase>();
        services.AddUseCase<InviteStudentAppCommand, StudentAppInvitationResponse, InviteStudentAppUseCase>();
        services.AddUseCase<AcceptStudentAppInvitationCommand, TokenResponse, AcceptStudentAppInvitationUseCase>();
        services.AddUseCase<CheckStudentAppInvitationCommand, CheckStudentAppInvitationResponse, CheckStudentAppInvitationUseCase>();
        services.AddUseCase<DeclineStudentAppInvitationCommand, DeclinedStudentAppInvitationResponse, DeclineStudentAppInvitationUseCase>();
        services.AddUseCase<CheckGuardianConsentCommand, GuardianConsentResponse, CheckGuardianConsentUseCase>();
        services.AddUseCase<GiveGuardianConsentCommand, GivenGuardianConsentResponse, GiveGuardianConsentUseCase>();
        services.AddUseCase<RefuseGuardianConsentCommand, RefusedGuardianConsentResponse, RefuseGuardianConsentUseCase>();
        services.AddUseCase<GiveGuardianConsentInAppCommand, GivenGuardianConsentResponse, GiveGuardianConsentInAppUseCase>();
        services.AddUseCase<RefuseGuardianConsentInAppCommand, RefusedGuardianConsentResponse, RefuseGuardianConsentInAppUseCase>();
        services.AddUseCase<ListRolesQuery, IReadOnlyList<RoleResponse>, ListRolesUseCase>();
        services.AddUseCase<CreateRoleCommand, RoleResponse, CreateRoleUseCase>();
        services.AddUseCase<UpdateRoleCommand, RoleResponse, UpdateRoleUseCase>();
        services.AddUseCase<DeleteRoleCommand, DeletedRoleResponse, DeleteRoleUseCase>();
        services.AddUseCase<AssignSubstituteCommand, SessionStatusResponse, AssignSubstituteUseCase>();
        services.AddUseCase<RemoveSubstituteCommand, SessionStatusResponse, RemoveSubstituteUseCase>();
        services.AddUseCase<SetDefaultMonthlyFeeCommand, BusinessResponse, SetDefaultMonthlyFeeUseCase>();
        services.AddUseCase<SetClientBillingPlanCommand, ClientBillingResponse, SetClientBillingPlanUseCase>();
        services.AddUseCase<DeleteDefaultMonthlyFeeChangeCommand, BusinessResponse, DeleteDefaultMonthlyFeeChangeUseCase>();
        services.AddUseCase<DeleteClientBillingPlanChangeCommand, ClientBillingResponse, DeleteClientBillingPlanChangeUseCase>();
        services.AddUseCase<ListClassPacksQuery, IReadOnlyList<ClassPackResponse>, ListClassPacksUseCase>();
        services.AddUseCase<CreateClassPackCommand, ClassPackResponse, CreateClassPackUseCase>();
        services.AddUseCase<UpdateClassPackCommand, ClassPackResponse, UpdateClassPackUseCase>();
        services.AddUseCase<SetClassPackActiveCommand, ClassPackResponse, SetClassPackActiveUseCase>();
        services.AddUseCase<AddClassPackImageCommand, ClassPackResponse, AddClassPackImageUseCase>();
        services.AddUseCase<RemoveClassPackImageCommand, ClassPackResponse, RemoveClassPackImageUseCase>();
        services.AddUseCase<ReorderClassPackImagesCommand, ClassPackResponse, ReorderClassPackImagesUseCase>();
        services.AddUseCase<SellClassPackCommand, ClassPackPurchaseResponse, SellClassPackUseCase>();
        services.AddUseCase<DeleteClassPackPurchaseCommand, ClassPackPurchaseResponse, DeleteClassPackPurchaseUseCase>();
        services.AddUseCase<GetClientClassBalanceQuery, ClassBalanceResponse, GetClientClassBalanceUseCase>();
        services.AddUseCase<ListProductsQuery, IReadOnlyList<ProductResponse>, ListProductsUseCase>();
        services.AddUseCase<CreateProductCommand, ProductResponse, CreateProductUseCase>();
        services.AddUseCase<UpdateProductCommand, ProductResponse, UpdateProductUseCase>();
        services.AddUseCase<SetProductActiveCommand, ProductResponse, SetProductActiveUseCase>();
        services.AddUseCase<AddProductImageCommand, ProductResponse, AddProductImageUseCase>();
        services.AddUseCase<RemoveProductImageCommand, ProductResponse, RemoveProductImageUseCase>();
        services.AddUseCase<ReorderProductImagesCommand, ProductResponse, ReorderProductImagesUseCase>();
        services.AddUseCase<RecordStockMovementCommand, ProductResponse, RecordStockMovementUseCase>();
        services.AddUseCase<ListStockMovementsQuery, IReadOnlyList<StockMovementResponse>, ListStockMovementsUseCase>();
        services.AddUseCase<ListOrdersQuery, IReadOnlyList<OrderResponse>, ListOrdersUseCase>();
        services.AddUseCase<GetOrderSummaryQuery, OrderSummaryResponse, GetOrderSummaryUseCase>();
        services.AddUseCase<CreateCounterSaleCommand, OrderResponse, CreateCounterSaleUseCase>();
        services.AddUseCase<MarkOrderDeliveredCommand, OrderResponse, MarkOrderDeliveredUseCase>();
        services.AddUseCase<RefundOrderCommand, OrderResponse, RefundOrderUseCase>();
        services.AddUseCase<ConfirmOrderPaymentCommand, OrderResponse, ConfirmOrderPaymentUseCase>();
        services.AddUseCase<CancelOrderCommand, OrderResponse, CancelOrderUseCase>();
        services.AddUseCase<MarkOrderReadyCommand, OrderResponse, MarkOrderReadyUseCase>();
        services.AddUseCase<ChooseOrderDeliveryCommand, OrderResponse, ChooseOrderDeliveryUseCase>();
        services.AddUseCase<ListDeliveryClassesQuery, IReadOnlyList<DeliveryClassResponse>, ListDeliveryClassesUseCase>();
        services.AddUseCase<ListClassDeliveriesQuery, IReadOnlyList<ClassDeliveryResponse>, ListClassDeliveriesUseCase>();
        services.AddUseCase<DeliverInClassCommand, ClassDeliveryResponse, DeliverInClassUseCase>();
        services.AddUseCase<CancelExpiredOrdersCommand, int, CancelExpiredOrdersUseCase>();
        services.AddUseCase<GetStudentAppShopQuery, StudentAppShopResponse, GetStudentAppShopUseCase>();
        services.AddUseCase<ListStudentAppOrdersQuery, IReadOnlyList<StudentAppOrderResponse>, ListStudentAppOrdersUseCase>();
        services.AddUseCase<PlaceStudentAppOrderCommand, StudentAppOrderResponse, PlaceStudentAppOrderUseCase>();
        services.AddUseCase<CancelStudentAppOrderCommand, StudentAppOrderResponse, CancelStudentAppOrderUseCase>();
        services.AddUseCase<RecordPaymentCommand, PaymentResponse, RecordPaymentUseCase>();
        services.AddUseCase<ListClientPaymentsQuery, IReadOnlyList<PaymentResponse>, ListClientPaymentsUseCase>();
        services.AddUseCase<DeletePaymentCommand, PaymentResponse, DeletePaymentUseCase>();
        services.AddUseCase<RestorePaymentCommand, PaymentResponse, RestorePaymentUseCase>();
        services.AddUseCase<ListMonthlyFeesQuery, MonthlyFeesResponse, ListMonthlyFeesUseCase>();
        services.AddUseCase<UpdateBusinessSettingsCommand, UpdateBusinessSettingsResponse, UpdateBusinessSettingsUseCase>();
        services.AddUseCase<GetAchievementSettingsQuery, AchievementSettingsResponse, GetAchievementSettingsUseCase>();
        services.AddUseCase<UpdateAchievementSettingsCommand, AchievementSettingsResponse, UpdateAchievementSettingsUseCase>();

        return services;
    }

    private static IServiceCollection AddUseCase<TCommand, TResponse, TUseCase>(this IServiceCollection services)
        where TUseCase : class, IUseCase<TCommand, TResponse>
    {
        services.AddScoped<TUseCase>();
        services.AddScoped<IUseCase<TCommand, TResponse>>(serviceProvider => new UseCasePipeline<TCommand, TResponse>(
            serviceProvider.GetRequiredService<TUseCase>(),
            serviceProvider.GetServices<IUseCaseBehavior<TCommand, TResponse>>()));

        return services;
    }
}
