using ClassManager.Core.Abstractions.Fees;
using ClassManager.Core.Abstractions.Security;
using ClassManager.Core.Abstractions.Time;
using ClassManager.Core.Services;
using ClassManager.Core.UseCases.Achievements;
using ClassManager.Core.UseCases.Announcements;
using ClassManager.Core.UseCases.Authentication;
using ClassManager.Core.UseCases.Branches;
using ClassManager.Core.UseCases.Brands;
using ClassManager.Core.UseCases.Businesses;
using ClassManager.Core.UseCases.ClassGroups;
using ClassManager.Core.UseCases.ClassPacks;
using ClassManager.Core.UseCases.Clients;
using ClassManager.Core.UseCases.Enrollments;
using ClassManager.Core.UseCases.Families;
using ClassManager.Core.UseCases.Fees;
using ClassManager.Core.UseCases.ImportExport;
using ClassManager.Core.UseCases.ImportExport.Instructors;
using ClassManager.Core.UseCases.ImportExport.Students;
using ClassManager.Core.UseCases.Instructors;
using ClassManager.Core.UseCases.Members;
using ClassManager.Core.UseCases.Orders;
using ClassManager.Core.UseCases.PrivateLessons;
using ClassManager.Core.UseCases.Products;
using ClassManager.Core.UseCases.Roles;
using ClassManager.Core.UseCases.Sessions;
using ClassManager.Core.UseCases.Students;
using ClassManager.Core.UseCases.TeamNotifications;
using ClassManager.ImportExport.Parsing;
using ClassManager.ImportExport.Tabular;
using ClassManager.ImportExport.Tabular.Csv;
using ClassManager.ImportExport.Xlsx;

namespace ClassManager.Api;

internal static class UseCaseServiceCollectionExtensions
{
    public static IServiceCollection AddUseCases(this IServiceCollection services)
    {
        services.AddSingleton(TimeProvider.System);
        services.AddScoped<IBusinessCalendarService, BusinessCalendarService>();
        services.AddScoped<IClassBalanceService, ClassBalanceService>();
        services.AddScoped<IAccessScopes, AccessScopes>();
        services.AddSingleton<CsvTabularReader>();
        services.AddSingleton(new XlsxTabularReader());
        services.AddSingleton<ITabularReader, XlsxOrCsvTabularReader>();
        services.AddSingleton<ITabularWriter, XlsxTabularWriter>();
        services.AddSingleton<IImportParser, ImportParser>();
        services.AddScoped<IImportModule, InstructorImportModule>();
        services.AddScoped<IImportModule, StudentImportModule>();

        services.AddScoped<IUseCase<SignUpOwnerCommand, TokenResponse>, SignUpOwnerUseCase>();
        services.AddScoped<IUseCase<GetImportSchemaQuery, ImportSchemaResponse>, GetImportSchemaUseCase>();
        services.AddScoped<IUseCase<PreviewImportCommand, ImportReport>, PreviewImportUseCase>();
        services.AddScoped<IUseCase<ImportFileCommand, ImportReport>, ImportFileUseCase>();
        services.AddScoped<IUseCase<GetImportTemplateQuery, ExportFile>, GetImportTemplateUseCase>();
        services.AddScoped<IUseCase<ExportQuery, ExportFile>, ExportUseCase>();
        services.AddScoped<IUseCase<SignInCommand, TokenResponse>, SignInUseCase>();
        services.AddScoped<IUseCase<ListAccountsQuery, IReadOnlyList<AccountResponse>>, ListAccountsUseCase>();
        services.AddScoped<IUseCase<RefreshSessionCommand, TokenResponse>, RefreshSessionUseCase>();
        services.AddScoped<IUseCase<SignOutCommand, SignOutResponse>, SignOutUseCase>();
        services.AddScoped<IUseCase<ResetPasswordCommand, ResetPasswordResponse>, ResetPasswordUseCase>();
        services.AddScoped<IUseCase<RequestPasswordResetCommand, RequestPasswordResetResponse>, RequestPasswordResetUseCase>();
        services.AddScoped<IUseCase<GetCurrentBusinessQuery, BusinessResponse>, GetCurrentBusinessUseCase>();
        services.AddScoped<IUseCase<GetBrandQuery, BrandResponse>, GetBrandUseCase>();
        services.AddScoped<IUseCase<UpdateBrandCommand, BrandResponse>, UpdateBrandUseCase>();
        services.AddScoped<IUseCase<SetBrandLogoCommand, BrandResponse>, SetBrandLogoUseCase>();
        services.AddScoped<IUseCase<RemoveBrandLogoCommand, BrandResponse>, RemoveBrandLogoUseCase>();
        services.AddScoped<IUseCase<GetBrandLogoQuery, BrandLogoFile>, GetBrandLogoUseCase>();
        services.AddScoped<IUseCase<GetCurrentMemberQuery, CurrentMemberResponse>, GetCurrentMemberUseCase>();
        services.AddScoped<IUseCase<GetTeamQuery, TeamResponse>, GetTeamUseCase>();
        services.AddScoped<IUseCase<InviteMemberCommand, InvitationResponse>, InviteMemberUseCase>();
        services.AddScoped<IUseCase<RevokeInvitationCommand, RevokedInvitationResponse>, RevokeInvitationUseCase>();
        services.AddScoped<IUseCase<ResendInvitationCommand, InvitationResponse>, ResendInvitationUseCase>();
        services.AddScoped<IUseCase<AcceptInvitationCommand, TokenResponse>, AcceptInvitationUseCase>();
        services.AddScoped<IUseCase<CheckInvitationCommand, CheckInvitationResponse>, CheckInvitationUseCase>();
        services.AddScoped<IUseCase<ChangeMemberRoleCommand, MemberResponse>, ChangeMemberRoleUseCase>();
        services.AddScoped<IUseCase<RemoveMemberCommand, RemovedMemberResponse>, RemoveMemberUseCase>();
        services.AddScoped<IUseCase<ListBranchesQuery, IReadOnlyList<BranchResponse>>, ListBranchesUseCase>();
        services.AddScoped<IUseCase<SwitchBranchCommand, TokenResponse>, SwitchBranchUseCase>();
        services.AddScoped<IUseCase<CreateBranchCommand, BranchResponse>, CreateBranchUseCase>();
        services.AddScoped<IUseCase<SetBrandOwnerCommand, BrandOwnerResponse>, SetBrandOwnerUseCase>();
        services.AddScoped<IUseCase<RegisterClientCommand, ClientDetailsResponse>, RegisterClientUseCase>();
        services.AddScoped<IUseCase<GetClientQuery, ClientDetailsResponse>, GetClientUseCase>();
        services.AddScoped<IUseCase<SearchClientsQuery, IReadOnlyList<ClientResponse>>, SearchClientsUseCase>();
        services.AddScoped<IUseCase<AddStudentCommand, StudentResponse>, AddStudentUseCase>();
        services.AddScoped<IUseCase<GetStudentQuery, StudentSummaryResponse>, GetStudentUseCase>();
        services.AddScoped<IUseCase<SearchStudentsQuery, IReadOnlyList<StudentSummaryResponse>>, SearchStudentsUseCase>();
        services.AddScoped<IUseCase<ListInstructorsQuery, IReadOnlyList<InstructorResponse>>, ListInstructorsUseCase>();
        services.AddScoped<IUseCase<CreateInstructorCommand, InstructorResponse>, CreateInstructorUseCase>();
        services.AddScoped<IUseCase<UpdateInstructorCommand, InstructorResponse>, UpdateInstructorUseCase>();
        services.AddScoped<IUseCase<SetInstructorActiveCommand, InstructorResponse>, SetInstructorActiveUseCase>();
        services.AddScoped<IUseCase<ListClassGroupsQuery, IReadOnlyList<ClassGroupResponse>>, ListClassGroupsUseCase>();
        services.AddScoped<IUseCase<GetClassGroupQuery, ClassGroupResponse>, GetClassGroupUseCase>();
        services.AddScoped<IUseCase<CreateClassGroupCommand, ClassGroupResponse>, CreateClassGroupUseCase>();
        services.AddScoped<IUseCase<UpdateClassGroupCommand, ClassGroupResponse>, UpdateClassGroupUseCase>();
        services.AddScoped<IUseCase<SetClassGroupActiveCommand, ClassGroupResponse>, SetClassGroupActiveUseCase>();
        services.AddScoped<IUseCase<EnrollStudentCommand, EnrollmentResponse>, EnrollStudentUseCase>();
        services.AddScoped<IUseCase<EndEnrollmentCommand, EndEnrollmentResponse>, EndEnrollmentUseCase>();
        services.AddScoped<IUseCase<ListClassRosterQuery, IReadOnlyList<RosterEntryResponse>>, ListClassRosterUseCase>();
        services.AddScoped<IUseCase<ListStudentEnrollmentsQuery, IReadOnlyList<StudentEnrollmentResponse>>, ListStudentEnrollmentsUseCase>();
        services.AddScoped<IUseCase<ListDaySessionsQuery, IReadOnlyList<DaySessionResponse>>, ListDaySessionsUseCase>();
        services.AddScoped<IUseCase<ListMonthCalendarQuery, MonthCalendarResponse>, ListMonthCalendarUseCase>();
        services.AddScoped<IUseCase<SchedulePrivateLessonCommand, IReadOnlyList<PrivateLessonResponse>>, SchedulePrivateLessonUseCase>();
        services.AddScoped<IUseCase<GetPrivateLessonQuery, PrivateLessonResponse>, GetPrivateLessonUseCase>();
        services.AddScoped<IUseCase<ReschedulePrivateLessonCommand, PrivateLessonResponse>, ReschedulePrivateLessonUseCase>();
        services.AddScoped<IUseCase<CancelPrivateLessonCommand, PrivateLessonResponse>, CancelPrivateLessonUseCase>();
        services.AddScoped<IUseCase<RestorePrivateLessonCommand, PrivateLessonResponse>, RestorePrivateLessonUseCase>();
        services.AddScoped<IUseCase<RecordPrivateLessonAttendanceCommand, RecordAttendanceResponse>, RecordPrivateLessonAttendanceUseCase>();
        services.AddScoped<IUseCase<DeletePrivateLessonCommand, DeletedPrivateLessonResponse>, DeletePrivateLessonUseCase>();
        services.AddScoped<IUseCase<GetSessionQuery, SessionDetailsResponse>, GetSessionUseCase>();
        services.AddScoped<IUseCase<RecordAttendanceCommand, RecordAttendanceResponse>, RecordAttendanceUseCase>();
        services.AddScoped<IUseCase<RecordClassFeedbackCommand, bool>, RecordClassFeedbackUseCase>();
        services.AddScoped<IUseCase<CancelSessionCommand, SessionStatusResponse>, CancelSessionUseCase>();
        services.AddScoped<IUseCase<RestoreSessionCommand, SessionStatusResponse>, RestoreSessionUseCase>();
        services.AddScoped<IUseCase<RescheduleSessionCommand, SessionStatusResponse>, RescheduleSessionUseCase>();
        services.AddScoped<IUseCase<RestoreSessionScheduleCommand, SessionStatusResponse>, RestoreSessionScheduleUseCase>();
        services.AddScoped<IUseCase<GetFamilyHomeQuery, FamilyHomeResponse>, GetFamilyHomeUseCase>();
        services.AddScoped<IUseCase<GetFamilyNewsQuery, FamilyNewsResponse>, GetFamilyNewsUseCase>();
        services.AddScoped<IUseCase<MarkFamilyNewsSeenCommand, bool>, MarkFamilyNewsSeenUseCase>();
        services.AddScoped<IUseCase<NotifyAbsenceCommand, bool>, NotifyAbsenceUseCase>();
        services.AddScoped<MakeupRepositories>();
        services.AddScoped<PackCreditRepositories>();
        services.AddScoped<IUseCase<GetFamilyPushKeyQuery, FamilyPushKeyResponse>, GetFamilyPushKeyUseCase>();
        services.AddScoped<IUseCase<SavePushSubscriptionCommand, bool>, SavePushSubscriptionUseCase>();
        services.AddScoped<IUseCase<RemovePushSubscriptionCommand, bool>, RemovePushSubscriptionUseCase>();
        services.AddScoped<IUseCase<GetTeamNotificationsQuery, TeamNotificationsResponse>, GetTeamNotificationsUseCase>();
        services.AddScoped<IUseCase<MarkTeamNotificationsSeenCommand, bool>, MarkTeamNotificationsSeenUseCase>();
        services.AddScoped<IUseCase<GetTeamPushKeyQuery, TeamPushKeyResponse>, GetTeamPushKeyUseCase>();
        services.AddScoped<IUseCase<SaveTeamPushSubscriptionCommand, bool>, SaveTeamPushSubscriptionUseCase>();
        services.AddScoped<IUseCase<RemoveTeamPushSubscriptionCommand, bool>, RemoveTeamPushSubscriptionUseCase>();
        services.AddScoped<IUseCase<GetFamilyMakeupsQuery, FamilyMakeupsResponse>, GetFamilyMakeupsUseCase>();
        services.AddScoped<IUseCase<BookMakeupCommand, bool>, BookMakeupUseCase>();
        services.AddScoped<IUseCase<CancelMakeupCommand, bool>, CancelMakeupUseCase>();
        services.AddScoped<IUseCase<GetFamilyPackClassesQuery, FamilyPackClassesResponse>, GetFamilyPackClassesUseCase>();
        services.AddScoped<IUseCase<BookPackClassCommand, bool>, BookPackClassUseCase>();
        services.AddScoped<IUseCase<CancelPackClassCommand, bool>, CancelPackClassUseCase>();
        services.AddScoped<IUseCase<WithdrawAbsenceCommand, bool>, WithdrawAbsenceUseCase>();
        services.AddScoped<IUseCase<CreateAnnouncementCommand, AnnouncementResponse>, CreateAnnouncementUseCase>();
        services.AddScoped<IUseCase<ListAnnouncementsQuery, IReadOnlyList<AnnouncementResponse>>, ListAnnouncementsUseCase>();
        services.AddScoped<IUseCase<DeleteAnnouncementCommand, bool>, DeleteAnnouncementUseCase>();
        services.AddScoped<IUseCase<InviteFamilyCommand, FamilyInvitationResponse>, InviteFamilyUseCase>();
        services.AddScoped<IUseCase<AcceptFamilyInvitationCommand, TokenResponse>, AcceptFamilyInvitationUseCase>();
        services.AddScoped<IUseCase<CheckFamilyInvitationCommand, CheckFamilyInvitationResponse>, CheckFamilyInvitationUseCase>();
        services.AddScoped<IUseCase<ListRolesQuery, IReadOnlyList<RoleResponse>>, ListRolesUseCase>();
        services.AddScoped<IUseCase<CreateRoleCommand, RoleResponse>, CreateRoleUseCase>();
        services.AddScoped<IUseCase<UpdateRoleCommand, RoleResponse>, UpdateRoleUseCase>();
        services.AddScoped<IUseCase<DeleteRoleCommand, DeletedRoleResponse>, DeleteRoleUseCase>();
        services.AddScoped<IUseCase<AssignSubstituteCommand, SessionStatusResponse>, AssignSubstituteUseCase>();
        services.AddScoped<IUseCase<RemoveSubstituteCommand, SessionStatusResponse>, RemoveSubstituteUseCase>();
        services.AddScoped<IUseCase<SetDefaultMonthlyFeeCommand, BusinessResponse>, SetDefaultMonthlyFeeUseCase>();
        services.AddScoped<IUseCase<SetClientBillingPlanCommand, ClientBillingResponse>, SetClientBillingPlanUseCase>();
        services.AddScoped<IUseCase<ListClassPacksQuery, IReadOnlyList<ClassPackResponse>>, ListClassPacksUseCase>();
        services.AddScoped<IUseCase<CreateClassPackCommand, ClassPackResponse>, CreateClassPackUseCase>();
        services.AddScoped<IUseCase<UpdateClassPackCommand, ClassPackResponse>, UpdateClassPackUseCase>();
        services.AddScoped<IUseCase<SetClassPackActiveCommand, ClassPackResponse>, SetClassPackActiveUseCase>();
        services.AddScoped<IUseCase<SellClassPackCommand, ClassPackPurchaseResponse>, SellClassPackUseCase>();
        services.AddScoped<IUseCase<DeleteClassPackPurchaseCommand, ClassPackPurchaseResponse>, DeleteClassPackPurchaseUseCase>();
        services.AddScoped<IUseCase<GetClientClassBalanceQuery, ClassBalanceResponse>, GetClientClassBalanceUseCase>();
        services.AddScoped<IUseCase<ListProductsQuery, IReadOnlyList<ProductResponse>>, ListProductsUseCase>();
        services.AddScoped<IUseCase<CreateProductCommand, ProductResponse>, CreateProductUseCase>();
        services.AddScoped<IUseCase<UpdateProductCommand, ProductResponse>, UpdateProductUseCase>();
        services.AddScoped<IUseCase<SetProductActiveCommand, ProductResponse>, SetProductActiveUseCase>();
        services.AddScoped<IUseCase<RecordStockMovementCommand, ProductResponse>, RecordStockMovementUseCase>();
        services.AddScoped<IUseCase<ListStockMovementsQuery, IReadOnlyList<StockMovementResponse>>, ListStockMovementsUseCase>();
        services.AddScoped<IUseCase<ListOrdersQuery, IReadOnlyList<OrderResponse>>, ListOrdersUseCase>();
        services.AddScoped<IUseCase<CreateCounterSaleCommand, OrderResponse>, CreateCounterSaleUseCase>();
        services.AddScoped<IUseCase<MarkOrderDeliveredCommand, OrderResponse>, MarkOrderDeliveredUseCase>();
        services.AddScoped<IUseCase<RefundOrderCommand, OrderResponse>, RefundOrderUseCase>();
        services.AddScoped<IUseCase<ConfirmOrderPaymentCommand, OrderResponse>, ConfirmOrderPaymentUseCase>();
        services.AddScoped<IUseCase<CancelOrderCommand, OrderResponse>, CancelOrderUseCase>();
        services.AddScoped<IUseCase<MarkOrderReadyCommand, OrderResponse>, MarkOrderReadyUseCase>();
        services.AddScoped<IUseCase<ChooseOrderDeliveryCommand, OrderResponse>, ChooseOrderDeliveryUseCase>();
        services.AddScoped<IUseCase<ListDeliveryClassesQuery, IReadOnlyList<DeliveryClassResponse>>, ListDeliveryClassesUseCase>();
        services.AddScoped<IUseCase<ListClassDeliveriesQuery, IReadOnlyList<ClassDeliveryResponse>>, ListClassDeliveriesUseCase>();
        services.AddScoped<IUseCase<DeliverInClassCommand, ClassDeliveryResponse>, DeliverInClassUseCase>();
        services.AddScoped<IUseCase<CancelExpiredOrdersCommand, int>, CancelExpiredOrdersUseCase>();
        services.AddScoped<IUseCase<GetFamilyShopQuery, FamilyShopResponse>, GetFamilyShopUseCase>();
        services.AddScoped<IUseCase<ListFamilyOrdersQuery, IReadOnlyList<FamilyOrderResponse>>, ListFamilyOrdersUseCase>();
        services.AddScoped<IUseCase<PlaceFamilyOrderCommand, FamilyOrderResponse>, PlaceFamilyOrderUseCase>();
        services.AddScoped<IUseCase<CancelFamilyOrderCommand, FamilyOrderResponse>, CancelFamilyOrderUseCase>();
        services.AddScoped<IUseCase<RecordPaymentCommand, PaymentResponse>, RecordPaymentUseCase>();
        services.AddScoped<IUseCase<ListClientPaymentsQuery, IReadOnlyList<PaymentResponse>>, ListClientPaymentsUseCase>();
        services.AddScoped<IUseCase<DeletePaymentCommand, PaymentResponse>, DeletePaymentUseCase>();
        services.AddScoped<IUseCase<ListMonthlyFeesQuery, MonthlyFeesResponse>, ListMonthlyFeesUseCase>();
        services.AddScoped<IUseCase<UpdateBusinessSettingsCommand, UpdateBusinessSettingsResponse>, UpdateBusinessSettingsUseCase>();
        services.AddScoped<IUseCase<GetAchievementSettingsQuery, AchievementSettingsResponse>, GetAchievementSettingsUseCase>();
        services.AddScoped<IUseCase<UpdateAchievementSettingsCommand, AchievementSettingsResponse>, UpdateAchievementSettingsUseCase>();

        return services;
    }
}
