<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>ClassManager.Core</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../ImportExport/ImportExport.csproj" />
    <ProjectReference Include="../Notifications/Notifications.csproj" />
    <ProjectReference Include="../Subscriptions/Subscriptions.csproj" />
    <ProjectReference Include="../Tenancy/Tenancy.csproj" />
  </ItemGroup>
</Project>
